#!/bin/sh

# These environment variables will be read by CMake
export TETRIS_BUILD_TYPE=Release
export TETRIS_DEPLOY_DMG=Yes

# First clean the previous builds
rm -rf Build

# Start CMake
CMAKE_DIR=Build/CMake/QtTetris
mkdir -p $CMAKE_DIR
cd $CMAKE_DIR
cmake ../../../QtTetris

cd Build/CMake/QtTetris
make VERBOSE=1 -w -j8

