# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /opt/local/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/francis/svn/tetris-challenge/QtTetris

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/francis/svn/tetris-challenge

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/francis/svn/tetris-challenge/CMakeFiles /Users/francis/svn/tetris-challenge/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/francis/svn/tetris-challenge/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named QtTetris

# Build rule for target.
QtTetris: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 QtTetris
.PHONY : QtTetris

# fast build rule for target.
QtTetris/fast:
	$(MAKE) -f CMakeFiles/QtTetris.dir/build.make CMakeFiles/QtTetris.dir/build
.PHONY : QtTetris/fast

#=============================================================================
# Target rules for targets named Tetris

# Build rule for target.
Tetris: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Tetris
.PHONY : Tetris

# fast build rule for target.
Tetris/fast:
	$(MAKE) -f Build/Darwin/i386/Release/Tetris/CMakeFiles/Tetris.dir/build.make Build/Darwin/i386/Release/Tetris/CMakeFiles/Tetris.dir/build
.PHONY : Tetris/fast

MainWindow.o: MainWindow.cpp.o
.PHONY : MainWindow.o

# target to build an object file
MainWindow.cpp.o:
	$(MAKE) -f CMakeFiles/QtTetris.dir/build.make CMakeFiles/QtTetris.dir/MainWindow.cpp.o
.PHONY : MainWindow.cpp.o

MainWindow.i: MainWindow.cpp.i
.PHONY : MainWindow.i

# target to preprocess a source file
MainWindow.cpp.i:
	$(MAKE) -f CMakeFiles/QtTetris.dir/build.make CMakeFiles/QtTetris.dir/MainWindow.cpp.i
.PHONY : MainWindow.cpp.i

MainWindow.s: MainWindow.cpp.s
.PHONY : MainWindow.s

# target to generate assembly for a file
MainWindow.cpp.s:
	$(MAKE) -f CMakeFiles/QtTetris.dir/build.make CMakeFiles/QtTetris.dir/MainWindow.cpp.s
.PHONY : MainWindow.cpp.s

TetrisWidget.o: TetrisWidget.cpp.o
.PHONY : TetrisWidget.o

# target to build an object file
TetrisWidget.cpp.o:
	$(MAKE) -f CMakeFiles/QtTetris.dir/build.make CMakeFiles/QtTetris.dir/TetrisWidget.cpp.o
.PHONY : TetrisWidget.cpp.o

TetrisWidget.i: TetrisWidget.cpp.i
.PHONY : TetrisWidget.i

# target to preprocess a source file
TetrisWidget.cpp.i:
	$(MAKE) -f CMakeFiles/QtTetris.dir/build.make CMakeFiles/QtTetris.dir/TetrisWidget.cpp.i
.PHONY : TetrisWidget.cpp.i

TetrisWidget.s: TetrisWidget.cpp.s
.PHONY : TetrisWidget.s

# target to generate assembly for a file
TetrisWidget.cpp.s:
	$(MAKE) -f CMakeFiles/QtTetris.dir/build.make CMakeFiles/QtTetris.dir/TetrisWidget.cpp.s
.PHONY : TetrisWidget.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/QtTetris.dir/build.make CMakeFiles/QtTetris.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/QtTetris.dir/build.make CMakeFiles/QtTetris.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/QtTetris.dir/build.make CMakeFiles/QtTetris.dir/main.cpp.s
.PHONY : main.cpp.s

moc_MainWindow.o: moc_MainWindow.cxx.o
.PHONY : moc_MainWindow.o

# target to build an object file
moc_MainWindow.cxx.o:
	$(MAKE) -f CMakeFiles/QtTetris.dir/build.make CMakeFiles/QtTetris.dir/moc_MainWindow.cxx.o
.PHONY : moc_MainWindow.cxx.o

moc_MainWindow.i: moc_MainWindow.cxx.i
.PHONY : moc_MainWindow.i

# target to preprocess a source file
moc_MainWindow.cxx.i:
	$(MAKE) -f CMakeFiles/QtTetris.dir/build.make CMakeFiles/QtTetris.dir/moc_MainWindow.cxx.i
.PHONY : moc_MainWindow.cxx.i

moc_MainWindow.s: moc_MainWindow.cxx.s
.PHONY : moc_MainWindow.s

# target to generate assembly for a file
moc_MainWindow.cxx.s:
	$(MAKE) -f CMakeFiles/QtTetris.dir/build.make CMakeFiles/QtTetris.dir/moc_MainWindow.cxx.s
.PHONY : moc_MainWindow.cxx.s

moc_TetrisWidget.o: moc_TetrisWidget.cxx.o
.PHONY : moc_TetrisWidget.o

# target to build an object file
moc_TetrisWidget.cxx.o:
	$(MAKE) -f CMakeFiles/QtTetris.dir/build.make CMakeFiles/QtTetris.dir/moc_TetrisWidget.cxx.o
.PHONY : moc_TetrisWidget.cxx.o

moc_TetrisWidget.i: moc_TetrisWidget.cxx.i
.PHONY : moc_TetrisWidget.i

# target to preprocess a source file
moc_TetrisWidget.cxx.i:
	$(MAKE) -f CMakeFiles/QtTetris.dir/build.make CMakeFiles/QtTetris.dir/moc_TetrisWidget.cxx.i
.PHONY : moc_TetrisWidget.cxx.i

moc_TetrisWidget.s: moc_TetrisWidget.cxx.s
.PHONY : moc_TetrisWidget.s

# target to generate assembly for a file
moc_TetrisWidget.cxx.s:
	$(MAKE) -f CMakeFiles/QtTetris.dir/build.make CMakeFiles/QtTetris.dir/moc_TetrisWidget.cxx.s
.PHONY : moc_TetrisWidget.cxx.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... QtTetris"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Tetris"
	@echo "... MainWindow.o"
	@echo "... MainWindow.i"
	@echo "... MainWindow.s"
	@echo "... TetrisWidget.o"
	@echo "... TetrisWidget.i"
	@echo "... TetrisWidget.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... moc_MainWindow.o"
	@echo "... moc_MainWindow.i"
	@echo "... moc_MainWindow.s"
	@echo "... moc_TetrisWidget.o"
	@echo "... moc_TetrisWidget.i"
	@echo "... moc_TetrisWidget.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

