#!/bin/sh
export CMAKE_PREFIX_PATH=/Users/francis/Qt5.6.2/5.6/clang_64/lib/cmake:/Users/francis/Qt5.6.2/5.6/clang_64/lib/cmake/Qt5:/Users/francis/Qt5.6.2/5.6/clang_64/lib/cmake/Qt5Gui
rm -rf Build
./configure
cd Build
make -j8
