#!/bin/bash
set -e

rm -rf Build-cmake
mkdir Build-cmake

cd Build-cmake

MAKEFLAGS=${MAKEFLAGS:--j7} conan install .. --build=missing 
cmake ..
make VERBOSE=1 -j7

# HACK:
# The binary needs to know where to find the Qt libs.
# We tell it to find look for the frameworks in the
# Qt installation directory where we found "moc".
QT_LIB_DIR="$(dirname "$(dirname $(which moc))")/lib"
install_name_tool -add_rpath $QT_LIB_DIR bin/QtTetris

# Run the unit tests 
Build-cmake/bin/TetrisTest

