#!/bin/sh

# If Qt is not installed 
which qmake || {
    printf "$(basename "$0"): *** qmake not found using your PATH. Please install Qt and update your PATH if necessary.\n" 1>&2
    exit 1
}

rm -rf Build && mkdir Build
(cd Build && cmake .. && make -j8)

[ -f Build/QtTetris/QtTetris ] && {
    echo "Build succeeded: Build/QtTetris/QtTetris"
}
