#!/bin/sh

# These environment variables will be read by CMake
export TETRIS_BUILD_TYPE=${TETRIS_BUILD_TYPE:-Debug}
export TETRIS_DEPLOY_DMG=${TETRIS_DEPLOY_DMG:-No}
export TETRIS_MINGW=${TETRIS_MINGW:-No}

cmake .
