#!/bin/sh

# These environment variables will be read by CMake
export TETRIS_BUILD_TYPE=${TETRIS_BUILD_TYPE:-Release}
export TETRIS_DEPLOY_DMG=${TETRIS_DEPLOY_DMG:-No}

MAIN_DIR=`pwd`
CMAKE_DIR=$MAIN_DIR/../Build/CMake/Tetris/testsuite
mkdir -p $CMAKE_DIR
cd $CMAKE_DIR
cmake $MAIN_DIR/Tetris/testsuite

echo "\nTo build TetrisTestSuite:"
echo "  cd $CMAKE_DIR"
echo "  make VERBOSE=1"
