#!/bin/bash
if [ $# -ne 2 ] ; then
    echo "Usage: `basename $0` <<namespace>> <<class>>"
    exit 65
fi

# Find the absolute dir of the script to find location of "Template.h" and "Template.cpp"
SCRIPT_PATH="`dirname $0`/`basename $0`"
SCRIPT_REAL_PATH="`readlink $SCRIPT_PATH`"
SCRIPT_REAL_DIR=`dirname $SCRIPT_REAL_PATH`

# Variables
NAMESPACE=$1
CLASS=$2
CLASS_UPCASE=`ruby -e "print \"$CLASS\".upcase"`

# Replace it
cat "${SCRIPT_REAL_DIR}/Template.h" | sed -e "s/CLASS_H/${CLASS_UPCASE}_H/" | sed -e "s/NAMESPACE/$NAMESPACE/g" | sed -e "s/CLASS/$CLASS/g" > "$CLASS.h"
cat "${SCRIPT_REAL_DIR}/Template.cpp" | sed -e "s/NAMESPACE/$NAMESPACE/g" | sed -e "s/CLASS/$CLASS/g" > "$CLASS.cpp"

